### ISSUE TITLE
Fail to execute the spark plan on k8s through spark connect

### ISSUE THREAD

**Issue by sparkdemotivator** [Wh1isper/sparglim#3]
* sparglim version: Latest version
* Python version: Same as the latest image in Jupiter lab in the repo
* Operating System: Ubuntu 22.04, minikube version: v1.31.2

### Description

Followed the guide here to deploy Jupiter lab and spark connect on k8s, but spark failed to execute the spark plan
https://github.com/Wh1isper/sparglim/tree/main/examples/jupyter-sparglim-sc

### What I Did

```
Install k8s through minikube
// Did the same as the guide 
kubectl create clusterrolebinding serviceaccounts-cluster-admin
  --clusterrole=cluster-admin
  --group=system:serviceaccounts
kubectl apply -f examples/jupyter-sparglim-sc/k8s/jupyter-sparglim/
kubectl apply -f examples/jupyter-sparglim-sc/k8s/sparglim-server/
```
After doing such, I was able to access Jupiter lab and using Jupiter lab to connect spark driver thru spark connect, but when i run the sample code given, spark failed to execute the plan and returned the error "**java.lang.ClassCastException: cannot assign instance of java.lang.invoke.SerializedLambda to field org.apache.spark.rdd.MapPartitionsRDD.f of type scala.Function3 in instance of org.apache.spark.rdd.MapPartitionsRDD**". Meanwhile, in spark UI, it shown that it failed to execute the plan with the above error

The log with error returned

![image](https://github.com/Wh1isper/sparglim/assets/147146130/380e081f-5642-4cfa-845b-1d533e187cee)

Sample code for testing

```
import os
os.environ["SPARGLIM_REMOTE"] = "sc://xxxx:30052" # or export SPARGLIM_REMOTE=sc://localhost:15002 before run python

from sparglim.config.builder import ConfigBuilder
from datetime import datetime, date
from pyspark.sql import Row


# c = ConfigBuilder().config_connect_client()
spark = c.get_or_create()

df = spark.createDataFrame([
    Row(a=1, b=2., c='string1', d=date(2000, 1, 1), e=datetime(2000, 1, 1, 12, 0)),
    Row(a=2, b=3., c='string2', d=date(2000, 2, 1), e=datetime(2000, 1, 2, 12, 0)),
    Row(a=4, b=5., c='string3', d=date(2000, 3, 1), e=datetime(2000, 1, 3, 12, 0))
])
df.show()
```

**Comment by Wh1isper** [comment]
Reproducible, there seems to be some issues with the build of [spark-executor](https://github.com/Wh1isper/spark-build#build-executor), standalone mode should be fine.

I'll fix this as soon as I can.

**Comment by Wh1isper** [comment]
Sorry for my laziness in not using dockerhub's executor image for testing, I missed the `spark-connect.jar` during the build and it caused the udf for the `spark connect server` to not work properly on `executor`.

I'm pushing a patch, please pull `wh1isper/spark-executor:3.4.1` later, after that it should work!

Also, I'd suggest re-pulling `wh1isper/sparglim-server` and `wh1isper/jupyterlab-sparglim` as well, I've fixed a few other issues in the builds.

**Comment by sparkdemotivator** [comment]
Thanks the problem has been resolved with the latest version
